
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'NuxtWelcome': typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyNuxtWelcome': typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const NuxtWelcome: typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtWelcome: typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
